# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'TouchSynthProject' do
	pod 'libpd', '~> 0.7'
	#pod 'MIKMIDI', '~> 1.0'
	pod 'MIKMIDI', :git => 'https://github.com/mixedinkey-opensource/MIKMIDI.git', :branch => '1.1'
    pod "ZFDragableModalTransition"

end

target 'TouchSynthProjectTests' do

end

