# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'TouchSynthProject' do
	pod 'libpd', '~> 0.7'
        pod "ZFDragableModalTransition"

end

target 'TouchSynthProjectTests' do

end

